# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TMVrlB0L18aL68Xa3gompK7SxCqOi7A
"""

import requests

BOT_TOKEN = ""

# Pedimos las actualizaciones al bot
url = f"https://api.telegram.org/bot{BOT_TOKEN}/getUpdates"
resp = requests.get(url).json()

# Mostramos el JSON completo para ver el chat_id
print(resp)

import requests

# Tu bot y chat
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""

# Mensaje de prueba
mensaje = "🚀 Prueba de mensaje desde Colab a Telegram ✅"

url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"

response = requests.post(url, data={
    "chat_id": TELEGRAM_CHAT_ID,
    "text": mensaje
})

print(response.status_code)
print(response.json())